ALTER TABLE FTCMEDCITEM ADD UCL NVARCHAR(200);
ALTER TABLE FTCMEDCITEM ADD LCL NVARCHAR(200);
ALTER TABLE FTCMEDCITEM ADD ACTIVE NVARCHAR(5);
ALTER TABLE FTCMEDCITEM ALTER COLUMN USL NVARCHAR(200);
ALTER TABLE FTCMEDCITEM ALTER COLUMN LSL NVARCHAR(200);
ALTER TABLE FTCMRECIPE ALTER COLUMN USL NVARCHAR(200);
ALTER TABLE FTCMRECIPE ALTER COLUMN LSL NVARCHAR(200);
ALTER TABLE FTCMRECIPE ALTER COLUMN UCL NVARCHAR(200);
ALTER TABLE FTCMRECIPE ALTER COLUMN LCL NVARCHAR(200);
ALTER TABLE FTCMRECIPE ALTER COLUMN ITEMVALUE NVARCHAR(200);

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'管制上限' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'FTCMEDCITEM', @level2type=N'COLUMN',@level2name=N'UCL'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'管制下限' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'FTCMEDCITEM', @level2type=N'COLUMN',@level2name=N'LCL'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'啟用，Y=啟用，N=不啟用' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'FTCMEDCITEM', @level2type=N'COLUMN',@level2name=N'ACTIVE'

update FTCMEDCITEM set ACTIVE='Y'
update FTCMEDCITEM set UCL=''
update FTCMEDCITEM set LCL=''