ALTER TABLE FTCEDCDATACOLLECTION ALTER COLUMN FACTORDATAID NVARCHAR(250);
ALTER TABLE FTCEDCDATACOLLECTIONONLINE ALTER COLUMN FACTORDATAID NVARCHAR(250);
ALTER TABLE FTCMEDCFACTORTYPE ALTER COLUMN FACTORDATAID NVARCHAR(250);
ALTER TABLE FTCMRECIPE ALTER COLUMN FACTORDATAID NVARCHAR(250);
