CREATE VIEW V_TreeNode
AS
SELECT DISTINCT A.USERID, C.NODEID, C.PARENTID, C.NODETEXT, C.NODETARGET, C.NODESEQUENCE, C.NODEURL, C.NODEIMAGE, B.CONTROLID, C.IFRAMEHEIGHT
FROM              dbo.COMM_USER_HAS_ROLES AS A LEFT OUTER JOIN
                            dbo.COMM_ROLENODE AS B ON A.ROLEID = B.ROLEID INNER JOIN
                            dbo.COMM_FUNCTIONLIST AS C ON B.NODEID = C.NODEID